### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Yomamma2020** [Txar/DeepScience#4]
When I try to make a Lum Crucible, I crash. I tried resetting my phone, the game, and the map, but it keeps crashing.

**Comment by SargeanTravis** [comment]
It still crashes? this happened to me earlier today, guess it isn't fixed yet?

**Comment by SargeanTravis** [comment]
It doesnt crash for me, but it's non-functional, just a place-able sprite. most likely a WIP

**Comment by Txar** [comment]
that's because @ThePythonGuy3 didn't disable the script finally, don't worry, I'ma fix it rn

**Comment by Txar** [comment]
![Screenshot_20200812-064408.png](https://user-images.githubusercontent.com/67731745/89975901-470d0800-dc67-11ea-9fd9-b263b8f908d0.png) fixed

**Comment by Yomamma2020** [comment]
Still happens, right when it's done building Mindustry crashes.

**Comment by Txar** [comment]
did you redownload it?

**Comment by Yomamma2020** [comment]
No, that's probably why

**Comment by ThePythonGuy3** [comment]
ohno
